theme = "maupassant"
baseURL = "http://superchun.cn"
languageCode = "zh-CN"
title = "悉达多｜PainMaker"
preserveTaxonomyNames = true
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

[author]
  name = "悉达多"

[params]
  author = "悉达多"
  subtitle = "知也者，所以知也，而不必知"
  busuanzi = true
  localSearch = true

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3

[params.cc]
  name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
  link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

# Utteranc 评论
[params.utteranc]
  enable = true
  repo = "cconecode/blogcomment"
  issueTerm = "pathname"
  theme = "github-light"

# Sequence 序列图
[params.dequenceDiagrams]
  enable = true
  options = ""

# Flowchar 流程图
[params.flowchartDiagrams]
  enable = true
  options = ""

# Google分析
googleAnalytics = "UA-153875253-1"
